In [1]:
import torch

In [2]:
A = torch.rand(3,3,2)

In [3]:
A = A.cuda()

In [4]:
A

tensor([[[0.5833, 0.8990],
         [0.6506, 0.9681],
         [0.9872, 0.9497]],

        [[0.8509, 0.2025],
         [0.5252, 0.9414],
         [0.0821, 0.4635]],

        [[0.5888, 0.2138],
         [0.2013, 0.1550],
         [0.6109, 0.9588]]], device='cuda:0')

In [5]:
def function(A):
    A = A + 1
    

In [6]:
function(A)

In [7]:
A

tensor([[[0.5833, 0.8990],
         [0.6506, 0.9681],
         [0.9872, 0.9497]],

        [[0.8509, 0.2025],
         [0.5252, 0.9414],
         [0.0821, 0.4635]],

        [[0.5888, 0.2138],
         [0.2013, 0.1550],
         [0.6109, 0.9588]]], device='cuda:0')

In [8]:
A = torch.rand(3,3,2)

In [9]:
A = A.cuda()

In [10]:
B = A.clone()

In [11]:
B += 1

In [12]:
B

tensor([[[1.8620, 1.7534],
         [1.1694, 1.5440],
         [1.3240, 1.3831]],

        [[1.4217, 1.5780],
         [1.7640, 1.7840],
         [1.3578, 1.1776]],

        [[1.0631, 1.5424],
         [1.5002, 1.0253],
         [1.6499, 1.1699]]], device='cuda:0')

In [13]:
getattr

tensor([[[0.8620, 0.7534],
         [0.1694, 0.5440],
         [0.3240, 0.3831]],

        [[0.4217, 0.5780],
         [0.7640, 0.7840],
         [0.3578, 0.1776]],

        [[0.0631, 0.5424],
         [0.5002, 0.0253],
         [0.6499, 0.1699]]], device='cuda:0')