In [1]:
import random

In [2]:
random()

TypeError: 'module' object is not callable

In [3]:
from random import random

In [4]:
random()

0.9597203692001196

In [13]:
def random():
    return random.random()

In [7]:
import random

In [9]:
random()

AttributeError: 'function' object has no attribute 'random'

In [10]:
random.random()

AttributeError: 'function' object has no attribute 'random'

In [11]:
import random

In [12]:
random.random()

0.5141608934698989

In [14]:
random()

AttributeError: 'function' object has no attribute 'random'

In [18]:
A = torch.rand(3,3,2).cuda()

In [17]:
import torch

In [19]:
A.device

device(type='cuda', index=0)

In [24]:
import torch.nn as nn
class Example(nn.Module):
    def set(self):
        temp = nn.Parameter(torch.zeros(1, 10, 1))
        self.__setattr__('exp_%s' % (str(1)),temp)

    def set_torch(self):
        conv1 = nn.Conv2d(128,256,3)
        # self.__setattr__('exp1',nn.ModuleList([conv1,conv1,conv1]))

example = Example()
example.set()
example.set_torch()
example.__getattr__('exp')
example.__getattr__('exp1')

ModuleAttributeError: 'Example' object has no attribute 'exp'

In [27]:
A = example.__getattr__('exp_1')

In [28]:
A += 1

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [29]:
A = A + 1

In [30]:
A

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]]], grad_fn=<AddBackward0>)

In [31]:
example.__getattr__('exp_1')

Parameter containing:
tensor([[[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.]]], requires_grad=True)

In [32]:
bbox = torch.randn(32,8,4)
s_idx = ((bbox[:, 3] - bbox[:, 1]) < 64) * ((bbox[:, 4] - bbox[:, 2]) < 64)

In [33]:
s_idx.size()

torch.Size([32, 4])

In [34]:
s_idx

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True,